In [1]:
import numpy as np

In [9]:
my_arr=np.arange(1000000)
my_list=list(range(1000000))

In [4]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 167 ms


In [10]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]


Wall time: 2.49 s


NumPy-based algorithms are generally 10 to 100 times faster (or more) than their
pure Python counterparts and use significantly less memory.

# Creating ndarrays

In [12]:
data1 = [6, 7.5, 8, 0, 1]

In [13]:
 arr1 = np.array(data1)

In [14]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [16]:
 data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)

In [17]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
arr2.ndim

2

In [19]:
arr2.shape

(2, 4)

In [20]:
arr1.dtype


dtype('float64')

In [21]:
 np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
#  To create a higher dimensional array with these methods, pass a tuple for the shape:

np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [24]:
np.empty((2, 3, 2))
'''It’s not safe to assume that np.empty will return an array of all
 zeros. In some cases, it may return uninitialized “garbage” values.'''

'It’s not safe to assume that np.empty will return an array of all\n zeros. In some cases, it may return uninitialized “garbage” values.'